#!/bin/bash

# User configuration
dir=/opt/etc

# Fixed configuration
ssh_key=$dir/fpga-ssh
username=root

if [ -e $dir/fpga-motd ]; then
    cat $dir/fpga-motd
fi

# The APC username and password are stored in a line beginning with
# "credentials" in info.txt.
credentials_apc=$(grep ^credentials-apc $dir/info.txt)
credentials_apc=${credentials_apc#*,}
username_apc=${credentials_apc%,*}
password_apc=${credentials_apc#*,}

# FPGA info is also in info.txt in a line beginning with "fpga"
fpgas=($(grep ^fpga $dir/info.txt))

awk 'BEGIN {printf "%-5s %-6s %-32s %-10s\n",
"FPGA", "STATUS", "CONFIG=md5(boot.bin)", "USER"}'
for fpga in "${fpgas[@]}"; do
    name=${fpga%%,*}
    tty=${fpga#*,}
    tty=${tty%%,*}
    power_strip=${fpga#*,*,}
    power_strip=${power_strip%%,*}
    plug=${fpga##*,}
    ip=$(grep ip $dir/info.txt | grep ,$power_strip, | awk -F',' '{print $3}')
    user=$(ps -A au | grep -i screen | grep $tty | tail -n1 | tail -n1 | \
        awk '{print $1}')
    status=$(exec fence_apc --action=status --ip=$ip --plug=$plug \
        --username=$username_apc --password=$password_apc | awk '{print $2}')
    if [ $status = "ON" ]; then
        # config=$(ssh -i $ssh_key -o ConnectTimeout=1 $username@$name \
        #     md5sum /mnt/boot/boot.bin 2>/dev/null | awk '{print $1}')
        config=$(ssh -i $ssh_key -o ConnectTimeout=1 $username@$name \
            "md5sum /mnt/boot/boot.bin" 2>/dev/null)
        return=$?
        if [ $return -ne 0 ]; then
            config="ssh-error-$return"
        else
            config=$(echo $config | awk '{print $1}')
        fi
    else
        config="fpga off no info"
    fi
    echo "$name $status $config $user" | \
        awk '{printf "%-5s %-6s %-32s %-10s\n", $1, $2, $3, $4}'
done
