#!/bin/bash
set -e

base_dir=`pwd`
uva_repo=git@gitlab.com:the-lone-gunmen

sync () {
    cd $1
    git remote add uva $2
    branch=`git log -n1 --pretty=oneline --decorate | awk '{print $3}' | sed 's/[,)]//g' | sed 's/^.\+\///'`
    # Do not try to sync merge commits
    if [[ $branch != Merge ]]; then
        git checkout `git log -n1 --pretty=oneline --decorate | awk '{print $3}' | sed 's/[,)]//g' | sed 's/^.\+\///'`;
        git push --force uva `git branch | grep \* | awk '{print $2}'`;
    fi
}

cat xfiles-dana/tools/scripts/known_hosts >> ~/.ssh/known_hosts
sync $base_dir/xfiles-dana/util/hdl-tools $uva_repo/hdl-tools
sync $base_dir/xfiles-dana/tests/rocc-software $uva_repo/rocc-software
sync $base_dir/xfiles-dana/tests $uva_repo/xfiles-dana-tests
sync $base_dir/xfiles-dana $uva_repo/xfiles-dana
sync $base_dir $uva_repo/rocket-chip
