#!/bin/bash
set -ex

base_dir=`pwd`
uva_repo=git@gitlab.com:the-lone-gunmen

sync () {
    cd $1
    git remote | grep SYNC || git remote add SYNC $2
    branch=`git branch | tail -n1 | xargs -n1 git checkout`
    # Do not try to sync merge commits
    if [[ $branch != Merge ]]; then
        git checkout $branch;
        git push --force SYNC `git branch | grep \* | awk '{print $2}'`;
    fi
}

cat xfiles-dana/tools/scripts/known_hosts >> ~/.ssh/known_hosts
sync $base_dir/xfiles-dana/util/hdl-tools $uva_repo/hdl-tools
sync $base_dir/xfiles-dana/tests/rocc-software $uva_repo/rocc-software
sync $base_dir/xfiles-dana/tests $uva_repo/xfiles-dana-tests
sync $base_dir/xfiles-dana $uva_repo/xfiles-dana
sync $base_dir $uva_repo/rocket-chip
