#!/bin/bash

base_dir=`pwd`
uva_repo=git@gitlab.com:the-lone-gunmen

sync () {
    cd $1
    echo git remote add uva $2
    echo git push uva `git branch | grep \* | awk '{print $2}'`
}

sync $base_dir $uva_repo/rocket-chip
sync $base_dir/xfiles-dana $uva_repo/xfiles-dana
sync $base_dir/xfiles-dana/tests $uva_repo/xfiles-dana-tests
sync $base_dir/xfiles-dana/tests/rocc-software $uva_repo/rocc-software
sync $base_dir/xfiles-dana/util/hdl-tools $uva_repo/hdl-tools
