#!/bin/bash

# Front-end script to open up

usage () {
    echo "Usage: $0 [VCD File]"
}

if [ $# -ne 1 ]
then
    usage
    exit
fi

FILE_VCD=$1
FILE_FST=${FILE_VCD%.*}.fst
FILE_GTKW=${FILE_VCD%.*}.gtkw

# Pass a truncated version of the VCD file to the addWavesRecursive
# script to generate the .gtkw save file
awk '/^#(([1\-9])|([0\-9][0\-9]))/{exit}1' $FILE_VCD | \
    gtkwave -v -S ../tools/scripts/addWavesRecursive.tcl > $FILE_GTKW
# Compress the VCD file to an FST file
vcd2fst $FILE_VCD $FILE_FST
# Open the FST file
gtkwave $FILE_FST $FILE_GTKW
