#!/bin/bash

usage () {
    echo "Usage: $0 [VCD File]"
}

if [ $# -ne 1 ]
then
    usage
    exit
fi

FILE_VCD=$1
FILE_GTKW=${FILE_VCD%.*}.gtkw

gtkwave -S ../tools/scripts/addWavesRecursive.tcl $FILE_VCD > $FILE_GTKW
gtkwave -o $FILE_VCD $FILE_GTKW
