#!/bin/bash

fpgas=($(grep ^fpga info.txt))
for fpga in "${fpgas[@]}"; do
    name=${fpga%%,*}
    tty=${fpga#*,}
    tty=${tty%%,*}
    # Check to see if we get a hit for that tty being in use
    ps -A au | grep -i screen | grep $tty 2>&1 > /dev/null
    if [[ $? -eq 1 ]]; then
        exec screen $tty 115200,cs8,-parenb,-cstopb
        exit 0
    fi
done

echo "[ERROR] All FPGAs in use. Use rvstatus/rvwho to check ownership."
exit 1
