#!/bin/bash

dir=$(dirname $(readlink -f $0))

# The APC username and password are stored in a line beginning with
# "credentials" in info.txt.
credentials_apc=$(grep ^credentials-apc $dir/info.txt)
credentials_apc=${credentials_apc#*,}
username_apc=${credentials_apc%,*}
password_apc=${credentials_apc#*,}

# FPGA info is also in info.txt in a line beginning with "fpga"
fpgas=($(grep ^fpga $dir/info.txt))

awk 'BEGIN {printf "%-6s %-7s %-10s\n", "FPGA", "STATUS", "USER"}'
for fpga in "${fpgas[@]}"; do
    name=${fpga%%,*}
    tty=${fpga#*,}
    tty=${tty%%,*}
    power_strip=${fpga#*,*,}
    power_strip=${power_strip%%,*}
    plug=${fpga##*,}
    ip=$(grep ip $dir/info.txt | grep ,$power_strip, | awk -F',' '{print $3}')
    user=$(ps -A au | grep -i screen | grep $tty | tail -n1 | tail -n1 | \
        awk '{print $1}')
    status=$(exec fence_apc --action=status --ip=$ip --plug=$plug \
        --username=$username_apc --password=$password_apc | awk '{print $2}')
    echo "$name $status $user" | awk '{printf "%-6s %-7s %-10s\n", $1, $2, $3}'
done
